-- Generated by npm run qr:generate. Contains token hashes only.
insert into public.cafe_tables (table_number, qr_token_hash, active)
values
  ('1', 'dc82240345cf2471291a10870855508d2e615e7f1c536ab64356db1234ed7395', true),
  ('2', '55bddcb9c491b6701e191f23082775eb04cdf5aaa2c1fae3345885e9a0cce647', true),
  ('3', '2ca0045b9219cf243bf1407a2382c638c90ca449b59918c5b2cc1692510b7acd', true)
on conflict (table_number) do update
set qr_token_hash = excluded.qr_token_hash,
    active = excluded.active,
    updated_at = now();
