import { createHash, randomBytes } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import QRCode from "qrcode";

try {
  process.loadEnvFile?.(".env.local");
} catch (error) {
  if (error?.code !== "ENOENT") throw error;
}

const rawBaseUrl = process.env.NEXT_PUBLIC_APP_URL;

if (!rawBaseUrl) {
  throw new Error("Set NEXT_PUBLIC_APP_URL in .env.local before generating QR codes.");
}

const parsedBaseUrl = new URL(rawBaseUrl);
if (!['http:', 'https:'].includes(parsedBaseUrl.protocol)) {
  throw new Error("NEXT_PUBLIC_APP_URL must be an http or https URL.");
}
if (["localhost", "127.0.0.1", "0.0.0.0", "::1"].includes(parsedBaseUrl.hostname)) {
  throw new Error(
    "Use a deployed domain or your LAN IP address instead of localhost for QR codes.",
  );
}

const baseUrl = parsedBaseUrl.href.replace(/\/$/, "");
const outputDirectory = resolve("public", "qrs");
const tokenSeedPath = resolve("supabase", "table-qr-token-seed.sql");
const envPath = resolve(".env.local");
await mkdir(outputDirectory, { recursive: true });

const tables = [1, 2, 3];
const entries = [];
let envContents = "";
try {
  envContents = await readFile(envPath, "utf8");
} catch (error) {
  if (error?.code !== "ENOENT") throw error;
}

function upsertEnvValue(contents, key, value) {
  const lines = contents ? contents.replace(/\r\n/g, "\n").split("\n") : [];
  const lineIndex = lines.findIndex((line) => line.startsWith(`${key}=`));
  const nextLine = `${key}=${value}`;
  if (lineIndex >= 0) {
    lines[lineIndex] = nextLine;
  } else {
    if (lines.length && lines.at(-1) !== "") lines.push("");
    lines.push(nextLine);
  }
  return `${lines.filter((line, index) => line || index < lines.length - 1).join("\n")}\n`;
}

const tokens = new Map();
let envChanged = false;

for (const table of tables) {
  const variableName = `YAPA_TABLE_${table}_QR_TOKEN`;
  let token = process.env[variableName]?.trim();
  if (!token) {
    token = randomBytes(32).toString("base64url");
    envContents = upsertEnvValue(envContents, variableName, token);
    envChanged = true;
  }
  if (!/^[A-Za-z0-9_-]{43,}$/.test(token)) {
    throw new Error(`${variableName} must contain at least 32 bytes of secure base64url data.`);
  }
  tokens.set(table, token);
}

if (envChanged) {
  await writeFile(envPath, envContents, "utf8");
}

const seedRows = [];

for (const table of tables) {
  const token = tokens.get(table);
  const url = new URL(`/menu/${table}`, `${baseUrl}/`);
  url.searchParams.set("table_qr_token", token);
  const filename = `table-${table}.png`;
  await QRCode.toFile(resolve(outputDirectory, filename), url.href, {
    errorCorrectionLevel: "H",
    margin: 3,
    width: 720,
    color: {
      dark: "#17110d",
      light: "#fffdf9",
    },
  });
  entries.push({
    table,
    urlPreview: `/menu/${table}?table_qr_token=••••••••`,
    image: `/qrs/${filename}`,
  });
  const tokenHash = createHash("sha256").update(token, "utf8").digest("hex");
  seedRows.push(`  ('${table}', '${tokenHash}', true)`);
}

await writeFile(
  resolve(outputDirectory, "manifest.json"),
  `${JSON.stringify({ baseUrl, entries }, null, 2)}\n`,
  "utf8",
);

await writeFile(
  tokenSeedPath,
  `-- Generated by npm run qr:generate. Contains token hashes only.\n` +
    `insert into public.cafe_tables (table_number, qr_token_hash, active)\n` +
    `values\n${seedRows.join(",\n")}\n` +
    `on conflict (table_number) do update\n` +
    `set qr_token_hash = excluded.qr_token_hash,\n` +
    `    active = excluded.active,\n` +
    `    updated_at = now();\n`,
  "utf8",
);

console.log("Generated tokenized QR codes and hash seed for Tables 1, 2, and 3.");
